# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lydia Barrett | Public Relations
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Public Relations - Communications - Copywriting
baseurl: "/startbootstrap-freelancer-jekyll" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
instagram_username: lalalifts
linkedin_url: https://www.linkedin.com/in/lydia-barrett-45977960/
#stackoverflow_url: https://
#googleplus_username: BobMarley
#skype_username: echo123

# Address information
address_street: 3034 Melrose Place
address_city: Beverly Hills
address_state: CA
address_zip: 90201

# Build settings
markdown: kramdown
sass:
  style: compressed
